### ISSUE TITLE
Add GDG DevFest Mumbai 2022 to 'Past In-person Events'.

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/events#4]
- We need to add GDG DevFest Mumbai 2022 to the 'Past In-person Events' section on the web site.
- Please add an event description along with pictures.
- Please mention the capacity in which OTC participated in the event.
	- Something along the lines of: Community Partner and helped in organising and volunteering.

**Comment by HarshKapadia2** [comment]
@SirusCodes let's add this?

**Comment by SirusCodes** [comment]
Yeah it's in my TODO list... Need to make some time for this

**Comment by SirusCodes** [comment]
Added it in https://github.com/OurTechCommunity/events/commit/e2749c89ade3c86211ca4551ece77f672f9bb0f7

Sorry forgot to reference this issue in commit message.
