### ISSUE TITLE
Add Women's Day 2023 Event

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/events#5]
Add the community-driven International Women's Day 2023 event that took place in Mumbai, to past in-person events.

**Comment by SirusCodes** [comment]
Yeah just forgot about it😅

**Comment by HarshKapadia2** [comment]
No issues. Please add it whenever you can, but preferably soon.

**Comment by SirusCodes** [comment]
Thanks🥰🥰

**Comment by HarshKapadia2** [comment]
No, thank you!
